import minVersion from 'semver/ranges/min-version.js'
import { resolveComma, toArray } from '../utils/general.ts'
import type { Logger } from '../utils/logger.ts'
import type { Ansis } from 'ansis'
import type { PackageJson } from 'pkg-types'

// Generated by `scripts/generate-target.ts`
const BASELINE_WIDELY_AVAILABLE_TARGET: string[] = [
  'chrome118',
  'edge118',
  'firefox119',
  'safari17',
  'ios17',
]

/**
 * Expand the special `'baseline-widely-available'` shorthand into its
 * concrete browser/runtime target strings.
 *
 * @param targets - Array of target strings, possibly containing the shorthand.
 * @returns Expanded target array with the shorthand replaced by the corresponding baseline browser versions.
 */
export function expandBaselineTarget(targets: string[]): string[] {
  return targets.flatMap((t) =>
    t === 'baseline-widely-available' ? BASELINE_WIDELY_AVAILABLE_TARGET : t,
  )
}

/**
 * Resolve the compilation target from the user config, falling back to the
 * minimum Node.js version declared in `package.json` `engines.node`.
 *
 * @param logger - Logger used to print the resolved targets.
 * @param target - Raw target option (`false` disables targeting entirely).
 * @param color - Ansis color function used to highlight target strings in logs.
 * @param pkg - Parsed `package.json`; used to infer a target from `engines.node` when `target` is omitted.
 * @param nameLabel - Optional build name label prepended to log lines.
 * @returns The resolved target strings, or `undefined` when targeting is disabled or cannot be inferred.
 */
export function resolveTarget(
  logger: Logger,
  target: string | string[] | false | undefined,
  color: Ansis,
  pkg?: PackageJson,
  nameLabel?: string,
): string[] | undefined {
  if (target === false) return
  if (target == null) {
    const pkgTarget = resolvePackageTarget(pkg)
    if (pkgTarget) {
      target = pkgTarget
    } else {
      return
    }
  }

  if (typeof target === 'number') {
    throw new TypeError(`Invalid target: ${target}`)
  }
  const targets = expandBaselineTarget(resolveComma(toArray(target)))
  if (targets.length)
    logger.info(
      nameLabel,
      `target${targets.length > 1 ? 's' : ''}: ${color(targets.join(', '))}`,
    )

  return targets
}

/**
 * Derive a Rolldown-compatible target string from `package.json`
 * `engines.node`, e.g. `'>=18'` → `'node18.0.0'`.
 *
 * @param pkg - Parsed `package.json`.
 * @returns A `nodeX.Y.Z` target string, or `undefined` if `engines.node` is absent or cannot be resolved to a concrete version.
 */
export function resolvePackageTarget(pkg?: PackageJson): string | undefined {
  const nodeVersion = pkg?.engines?.node
  if (!nodeVersion) return
  const nodeMinVersion = minVersion(nodeVersion)
  if (!nodeMinVersion) return
  if (nodeMinVersion.version === '0.0.0') return
  return `node${nodeMinVersion.version}`
}
