import { globSync } from 'node:fs'
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { format, resolveConfig, type Options } from 'prettier'
import {
  createFormatter,
  createParser,
  DEFAULT_CONFIG,
  SchemaGenerator,
  ts,
  type CompletedConfig,
  type Config,
  type Definition,
  type Schema,
} from 'ts-json-schema-generator'

const ROOT_DIR = path.join(import.meta.dirname, '..')

const SCHEMAS_DIR = path.join(ROOT_DIR, 'docs', 'public')

// const DEFAULT_INPUT_FILE_PATH = path.join(ROOT_DIR, 'src', 'index.ts')

const rootNames = globSync(
  [
    'src/**/*.?(c|m)ts?(x)',
    'packages/{css,exe}/src/**/*.?(c|m)ts?(x)',
    // '**/*.?(c|m)ts?(x)',
  ],
  {
    cwd: ROOT_DIR,
    exclude: [
      '__snapshots__/tsnapi/**',
      '**/dist',
      '**/fixtures',
      '**/node_modules',
      '**/temp',
      'dist/**',
      'docs/**',
      '**/*.{test,spec}?(-d).?(c|m)ts?(x)',
      'tests/**',
    ],
  },
)

const OUTPUT_FILE_SUFFIX = '.schema.json'

const DEFAULT_PRETTIER_OPTIONS = {
  endOfLine: 'lf',
  objectWrap: 'collapse',
  parser: 'json',
} as const satisfies Options

const compilerOptions = {
  allowImportingTsExtensions: true,
  allowJs: false,
  allowSyntheticDefaultImports: true,
  allowUnreachableCode: false,
  allowUnusedLabels: false,
  checkJs: false,
  declaration: true,
  declarationMap: true,
  emitDeclarationOnly: true,
  erasableSyntaxOnly: true,
  esModuleInterop: true,
  forceConsistentCasingInFileNames: true,
  isolatedModules: true,
  jsx: ts.JsxEmit.ReactJSX,
  lib: ['lib.esnext.d.ts', 'lib.dom.d.ts'],
  libReplacement: false,
  module: ts.ModuleKind.NodeNext,
  moduleDetection: ts.ModuleDetectionKind.Force,
  moduleResolution: ts.ModuleResolutionKind.NodeNext,
  noEmit: false,
  noEmitOnError: true,
  noErrorTruncation: true,
  noFallthroughCasesInSwitch: true,
  noUncheckedSideEffectImports: true,
  noUnusedLocals: false,
  noUnusedParameters: false,
  outDir: path.join(ROOT_DIR, 'dist').replaceAll('\\', '/'),
  rewriteRelativeImportExtensions: true,
  rootDir: path.join(ROOT_DIR, 'src').replaceAll('\\', '/'),
  skipLibCheck: true,
  sourceMap: true,
  strict: true,
  target: ts.ScriptTarget.ESNext,
  types: ['node'],
  useDefineForClassFields: true,
  useUnknownInCatchVariables: true,
  verbatimModuleSyntax: true,
} as const satisfies ts.CompilerOptions

const host = ts.createCompilerHost(compilerOptions, true)

const tsProgram = ts.createProgram({
  host,
  options: compilerOptions,
  rootNames,
})

type Entry = {
  /**
   * The output file name for the generated JSON schema. The file will be
   * created in the {@linkcode SCHEMAS_DIR} directory.
   */
  outputFile: string

  /**
   * Allows overriding default configuration for the schema generator on a
   * per-entry basis.
   *
   * @default {}
   */
  overrideConfig?: Config
}

type EntryWithSchema = Entry & {
  /**
   * The generated JSON schema for the entry. This will be generated using the
   * {@linkcode EntryWithSchema.schemaGeneratorConfig | schemaGeneratorConfig}
   * configuration.
   */
  schema: Schema

  /**
   * The configuration used to generate the JSON schema for the entry. This
   * will be generated by merging the {@linkcode defaultSchemaGeneratorConfig}
   * with the {@linkcode Entry.overrideConfig | overrideConfig} for the entry.
   */
  schemaGeneratorConfig: Config
}

const entries = {
  tsdownConfig: {
    outputFile: 'tsdown.config',
    overrideConfig: {
      path: 'src/index.ts',
      type: ['*'],
    },
  },
} as const satisfies Record<string, Entry>

const defaultSchemaGeneratorConfig = {
  ...DEFAULT_CONFIG,
  additionalProperties: false,
  discriminatorType: 'json-schema',
  encodeRefs: true,
  expose: 'export',
  extraTags: ['deprecationMessage', 'markdownDeprecationMessage'],
  fullDescription: false,
  functions: 'hide',
  jsDoc: 'extended',
  markdownDescription: true,
  minify: false,
  path: 'src/**/*.ts',
  skipTypeCheck: false,
  sortProps: true,
  strictTuples: true,
  topRef: true,
  tsconfig: path.join(ROOT_DIR, 'tsconfig.json'),
  tsProgram,
  type: ['*'],
} as const satisfies Config satisfies CompletedConfig

const objectConfig = Object.values(entries).map((entry) => {
  const entryOverrideConfig = entry.overrideConfig ?? ({} satisfies Config)

  const entryPath =
    'path' in entryOverrideConfig &&
    typeof entryOverrideConfig.path === 'string'
      ? entryOverrideConfig.path
      : defaultSchemaGeneratorConfig.path

  const entryType =
    'type' in entryOverrideConfig &&
    (typeof entryOverrideConfig.type === 'string' ||
      (Array.isArray(entryOverrideConfig.type) &&
        entryOverrideConfig.type.every(
          (typeName) => typeof typeName === 'string',
        )))
      ? entryOverrideConfig.type
      : defaultSchemaGeneratorConfig.type

  const schemaGeneratorConfig = {
    ...defaultSchemaGeneratorConfig,

    path: path.isAbsolute(entryPath)
      ? entryPath
      : path.join(ROOT_DIR, entryPath),

    type: Array.isArray(entryType) ? entryType : [entryType],
  } as const satisfies Config satisfies CompletedConfig

  const parser = createParser(tsProgram, schemaGeneratorConfig)

  const formatter = createFormatter(schemaGeneratorConfig)

  const schemaGenerator = new SchemaGenerator(
    tsProgram,
    parser,
    formatter,
    schemaGeneratorConfig,
  )

  // const schemaGenerator = createGenerator(schemaGeneratorConfig)

  return {
    outputFile: path.join(
      SCHEMAS_DIR,
      entry.outputFile.endsWith(OUTPUT_FILE_SUFFIX)
        ? entry.outputFile
        : `${entry.outputFile}${OUTPUT_FILE_SUFFIX}`,
    ),
    schemaGenerator,
    schemaGeneratorConfig,
  } as const satisfies Omit<EntryWithSchema, 'schema'> & {
    schemaGenerator: SchemaGenerator
  }
})

/**
 * Takes a string and returns the same string with
 * the first letter converted to lowercase.
 * The function version of the native
 * {@linkcode Uncapitalize} utility type in TypeScript.
 *
 * @param inputString - String that is going to be uncapitalized.
 * @returns Uncapitalized version of the {@linkcode inputString | input string}.
 *
 * @template StringToCapitalize - The type of the input string. This is used to preserve the string literal type of the input string in the output.
 *
 * @see {@linkcode Uncapitalize}
 */
function unCapitalize<StringToCapitalize extends string>(
  inputString: StringToCapitalize,
): Uncapitalize<StringToCapitalize> {
  return (inputString.charAt(0).toLowerCase() +
    inputString.slice(1)) as Uncapitalize<StringToCapitalize>
}

const schemas = objectConfig.map(
  ({ outputFile, schemaGenerator, schemaGeneratorConfig }) => {
    const schema = schemaGenerator.createSchema([
      // 'AttwOptions',
      // 'CheckPackageOptions',
      // 'ChunkAddon',
      // 'ChunkAddonObject',
      // 'CIOption',
      // 'CopyEntry',
      // 'CopyOptions',
      // 'CssOptions',
      // 'DevtoolsOptions',
      // 'DtsOptions',
      // 'ExportsOptions',
      // 'Format',
      // 'LogLevel',
      // 'LogType',
      // 'NormalizedFormat',
      // 'PackageJsonWithPath',
      // 'PackageType',
      // 'PackFile',
      // 'PublintOptions',
      // 'ReportOptions',
      // 'Sourcemap',
      // 'TsConfigJson.CompilerOptions.FallbackPolling',
      // 'TsConfigJson.CompilerOptions.IgnoreDeprecations',
      // 'TsConfigJson.CompilerOptions.ImportsNotUsedAsValues',
      // 'TsConfigJson.CompilerOptions.JSX',
      // 'TsConfigJson.CompilerOptions.Lib',
      // 'TsConfigJson.CompilerOptions.Module',
      // 'TsConfigJson.CompilerOptions.ModuleDetection',
      // 'TsConfigJson.CompilerOptions.ModuleResolution',
      // 'TsConfigJson.CompilerOptions.NewLine',
      // 'TsConfigJson.CompilerOptions.Plugin',
      // 'TsConfigJson.CompilerOptions.Target',
      // 'TsConfigJson.CompilerOptions.WatchDirectory',
      // 'TsConfigJson.CompilerOptions.WatchFile',
      // 'TsConfigJson.CompilerOptions',
      // 'TsConfigJson.References',
      // 'TsConfigJson.TypeAcquisition',
      // 'TsConfigJson.WatchOptions.PollingWatchKind',
      // 'TsConfigJson.WatchOptions.WatchDirectoryKind',
      // 'TsConfigJson.WatchOptions.WatchFileKind',
      // 'TsConfigJson.WatchOptions',
      // 'TsdownInputOption',
      // 'Workspace',
      'UserConfig',
    ])

    if (schema.definitions) {
      const newSchemaDefinitions = Object.fromEntries<Definition>(
        Object.entries(schema.definitions)
          .filter(
            (entry): entry is [string, Definition] =>
              typeof entry[1] === 'object' && entry[1] !== null,
          )
          .map(([definitionKey, definition]) => {
            if (
              definitionKey === 'PackageJsonWithPath' &&
              'properties' in definition &&
              typeof definition.properties === 'object' &&
              definition.properties !== null &&
              'packageJsonPath' in definition.properties &&
              typeof definition.properties.packageJsonPath === 'object' &&
              definition.properties.packageJsonPath !== null
            ) {
              const $ref = 'https://www.schemastore.org/package.json'

              const newDefinition = {
                ...definition,
                allOf: [
                  { $ref },
                  {
                    properties: {
                      packageJsonPath: {
                        ...definition.properties.packageJsonPath,
                      },
                    },
                  },
                ],
              } satisfies Definition

              return [definitionKey, newDefinition] as const satisfies [
                definitionKey: string,
                newDefinition: Definition,
              ]
            }

            if (definitionKey.startsWith('TsConfigJson.')) {
              const configKey = definitionKey.replace('TsConfigJson.', '')

              const configKeysSegments = configKey.split('.')

              if (configKeysSegments.length > 1) {
                // delete schema.definitions?.[definitionKey]

                // const firstConfigKeySegment = configKeysSegments[0] ?? ''

                // const unCapitalizedFirstConfigKeySegment = unCapitalize(
                //   firstConfigKeySegment,
                // )

                // const lastConfigKeySegment = configKeysSegments.at(-1) ?? ''

                // const unCapitalizedLastConfigKeySegment =
                //   unCapitalize(lastConfigKeySegment)

                // const $ref = `https://www.schemastore.org/tsconfig.json#/definitions/${unCapitalizedFirstConfigKeySegment}Definition/properties/${unCapitalizedLastConfigKeySegment}`

                // const newDefinition = {
                //   $ref,
                // } satisfies Definition

                return [definitionKey, null] as const satisfies [
                  definitionKey: string,
                  newDefinition: null,
                ]
              }

              const unCapitalizedConfigKey = unCapitalize(configKey)

              const $ref = `https://www.schemastore.org/tsconfig.json#/definitions/${unCapitalizedConfigKey}Definition/properties/${unCapitalizedConfigKey}`

              const newDefinition = {
                $ref,
              } satisfies Definition

              // schema.definitions[definitionKey] = {
              //   $ref,
              // }

              return [definitionKey, newDefinition] as const satisfies [
                definitionKey: string,
                newDefinition: Definition,
              ]
            }

            return [definitionKey, definition] as const satisfies [
              definitionKey: string,
              newDefinition: Definition | boolean,
            ]
          })
          .filter((entry) => entry[1] != null),
      )

      schema.definitions = newSchemaDefinitions
    }

    return {
      outputFile,
      schema,
      schemaGeneratorConfig,
    } as const satisfies EntryWithSchema
  },
)

const stringifiedSchemas = await Promise.all(
  schemas.map(async ({ outputFile, schema, schemaGeneratorConfig }) => {
    const stringifiedSchema = JSON.stringify(schema)

    const resolvedPrettierConfig = await resolveConfig(outputFile, {
      config: path.join(ROOT_DIR, 'package.json'),
    })

    const formattedSchema = await format(stringifiedSchema, {
      ...DEFAULT_PRETTIER_OPTIONS,
      ...(resolvedPrettierConfig ?? ({} satisfies Options)),
      filepath: outputFile,
    })

    return {
      formattedSchema,
      outputFile,
      schema,
      schemaGeneratorConfig,
      stringifiedSchema,
    } as const satisfies EntryWithSchema & {
      formattedSchema: string
      stringifiedSchema: string
    }
  }),
)

const createJsonSchema = async () => {
  await Promise.all(
    stringifiedSchemas.map(({ outputFile, formattedSchema }) =>
      fs.writeFile(outputFile, formattedSchema, { encoding: 'utf8' }),
    ),
  )
}

createJsonSchema()
