import { globSync } from 'node:fs'
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { format, resolveConfig, type Options } from 'prettier'
import {
  createGenerator,
  DEFAULT_CONFIG,
  ts,
  type CompletedConfig,
  type Config,
  type Schema,
  type SchemaGenerator,
} from 'ts-json-schema-generator'

const ROOT_DIR = path.join(import.meta.dirname, '..')

const SCHEMAS_DIR = path.join(ROOT_DIR, 'docs', 'public')

const DEFAULT_INPUT_FILE_PATH = path.join(ROOT_DIR, 'src', 'index.ts')

const rootNames = globSync(
  ['src/**/*.ts', 'packages/css/**/*.ts', 'packages/exe/**/*.ts'],
  {
    cwd: ROOT_DIR,
    exclude: [
      '__snapshots__/tsnapi/**',
      '**/dist',
      '**/fixtures',
      '**/node_modules',
      '**/temp',
      'dist/**',
      'docs/**',
      '**/*.spec.ts*',
      '**/*.test.ts*',
      'tests/**',
    ],
  },
)

const OUTPUT_FILE_SUFFIX = '.schema.json'

const DEFAULT_PRETTIER_OPTIONS = {
  endOfLine: 'lf',
  objectWrap: 'collapse',
  parser: 'json',
} as const satisfies Options

const compilerOptions = {
  allowImportingTsExtensions: true,
  allowJs: false,
  allowSyntheticDefaultImports: true,
  allowUnreachableCode: false,
  allowUnusedLabels: false,
  checkJs: false,
  declaration: true,
  declarationMap: true,
  emitDeclarationOnly: true,
  erasableSyntaxOnly: true,
  esModuleInterop: true,
  forceConsistentCasingInFileNames: true,
  isolatedModules: true,
  jsx: ts.JsxEmit.ReactJSX,
  lib: ['lib.esnext.d.ts', 'lib.dom.d.ts'],
  libReplacement: false,
  module: ts.ModuleKind.NodeNext,
  moduleDetection: ts.ModuleDetectionKind.Force,
  moduleResolution: ts.ModuleResolutionKind.NodeNext,
  noEmit: false,
  noEmitOnError: true,
  noErrorTruncation: true,
  noFallthroughCasesInSwitch: true,
  noUncheckedSideEffectImports: true,
  noUnusedLocals: false,
  noUnusedParameters: false,
  outDir: path.join(ROOT_DIR, 'dist').replaceAll('\\', '/'),
  rewriteRelativeImportExtensions: true,
  rootDir: path.join(ROOT_DIR, 'src').replaceAll('\\', '/'),
  skipLibCheck: true,
  sourceMap: true,
  strict: true,
  target: ts.ScriptTarget.ESNext,
  types: ['node'],
  useDefineForClassFields: true,
  useUnknownInCatchVariables: true,
  verbatimModuleSyntax: true,
} as const satisfies ts.CompilerOptions

const host = ts.createCompilerHost(compilerOptions, true)

const tsProgram = ts.createProgram({
  host,
  options: compilerOptions,
  rootNames,
})

type Entry = {
  /**
   * The output file name for the generated JSON schema. The file will be
   * created in the {@linkcode SCHEMAS_DIR} directory.
   */
  outputFile: string

  /**
   * Allows overriding default configuration for the schema generator on a
   * per-entry basis.
   *
   * @default {}
   */
  overrideConfig?: Config
}

type EntryWithSchema = Entry & {
  /**
   * The generated JSON schema for the entry. This will be generated using the
   * {@linkcode schemaGeneratorConfig} configuration.
   */
  schema: Schema

  /**
   * The configuration used to generate the JSON schema for the entry. This
   * will be generated by merging the {@linkcode defaultSchemaGeneratorConfig}
   * with the {@linkcode Entry.overrideConfig | overrideConfig} for the entry.
   */
  schemaGeneratorConfig: Config
}

const entries = {
  tsdownConfig: {
    outputFile: 'tsdown.config',
    overrideConfig: {
      path: 'src/index.ts',
      type: ['UserConfig'],
    },
  },
} as const satisfies Record<string, Entry>

const defaultSchemaGeneratorConfig = {
  ...DEFAULT_CONFIG,
  additionalProperties: false,
  discriminatorType: 'json-schema',
  encodeRefs: true,
  expose: 'export',
  extraTags: [],
  fullDescription: false,
  functions: 'hide',
  jsDoc: 'extended',
  markdownDescription: true,
  minify: false,
  path: DEFAULT_INPUT_FILE_PATH,
  skipTypeCheck: false,
  sortProps: true,
  strictTuples: true,
  topRef: true,
  tsconfig: path.join(ROOT_DIR, 'tsconfig.json'),
  tsProgram,
  type: ['*'],
} as const satisfies Config satisfies CompletedConfig

const objectConfig = Object.values(entries).map((entry) => {
  const entryOverrideConfig = entry.overrideConfig ?? ({} satisfies Config)

  const entryPath =
    entryOverrideConfig.path ?? defaultSchemaGeneratorConfig.path

  const entryType =
    entryOverrideConfig.type ?? defaultSchemaGeneratorConfig.type

  const schemaGeneratorConfig = {
    ...defaultSchemaGeneratorConfig,

    path: path.isAbsolute(entryPath)
      ? entryPath
      : path.join(ROOT_DIR, entryPath),

    type: Array.isArray(entryType) ? entryType : [entryType],
  } as const satisfies Config satisfies CompletedConfig

  const schemaGenerator = createGenerator(schemaGeneratorConfig)

  return {
    outputFile: path.join(
      SCHEMAS_DIR,
      entry.outputFile.endsWith(OUTPUT_FILE_SUFFIX)
        ? entry.outputFile
        : `${entry.outputFile}${OUTPUT_FILE_SUFFIX}`,
    ),
    schemaGenerator,
    schemaGeneratorConfig,
  } as const satisfies Omit<EntryWithSchema, 'schema'> & {
    schemaGenerator: SchemaGenerator
  }
})

const schemas = objectConfig.map(
  ({ outputFile, schemaGenerator, schemaGeneratorConfig }) => {
    const schema = schemaGenerator.createSchema([
      // 'AttwOptions',
      // 'CheckPackageOptions',
      // 'ChunkAddon',
      // 'ChunkAddonObject',
      // 'CIOption',
      // 'CopyEntry',
      // 'CopyOptions',
      // 'CssOptions',
      // 'DevtoolsOptions',
      // 'ExportsOptions',
      // 'Format',
      // 'LogLevel',
      // 'LogType',
      // 'NormalizedFormat',
      // 'PackageJsonWithPath',
      // 'PackageType',
      // 'PackFile',
      // 'PublintOptions',
      // 'ReportOptions',
      // 'Sourcemap',
      // 'TsConfigJson.CompilerOptions.FallbackPolling',
      // 'TsConfigJson.CompilerOptions.IgnoreDeprecations',
      // 'TsConfigJson.CompilerOptions.ImportsNotUsedAsValues',
      // 'TsConfigJson.CompilerOptions.JSX',
      // 'TsConfigJson.CompilerOptions.Lib',
      // 'TsConfigJson.CompilerOptions.Module',
      // 'TsConfigJson.CompilerOptions.ModuleDetection',
      // 'TsConfigJson.CompilerOptions.ModuleResolution',
      // 'TsConfigJson.CompilerOptions.NewLine',
      // 'TsConfigJson.CompilerOptions.Plugin',
      // 'TsConfigJson.CompilerOptions.Target',
      // 'TsConfigJson.CompilerOptions.WatchDirectory',
      // 'TsConfigJson.CompilerOptions.WatchFile',
      // 'TsConfigJson.CompilerOptions',
      // 'TsConfigJson.References',
      // 'TsConfigJson.TypeAcquisition',
      // 'TsConfigJson.WatchOptions.PollingWatchKind',
      // 'TsConfigJson.WatchOptions.WatchDirectoryKind',
      // 'TsConfigJson.WatchOptions.WatchFileKind',
      // 'TsConfigJson.WatchOptions',
      // 'TsdownInputOption',
      // 'Workspace',
      'UserConfig',
    ])

    return {
      outputFile,
      schema,
      schemaGeneratorConfig,
    } as const satisfies EntryWithSchema
  },
)

const stringifiedSchemas = await Promise.all(
  schemas.map(async ({ outputFile, schema, schemaGeneratorConfig }) => {
    const stringifiedSchema = JSON.stringify(schema)

    const resolvedPrettierConfig = await resolveConfig(outputFile, {
      config: path.join(ROOT_DIR, 'package.json'),
    })

    const formattedSchema = await format(stringifiedSchema, {
      ...DEFAULT_PRETTIER_OPTIONS,
      ...(resolvedPrettierConfig ?? ({} satisfies Options)),
      filepath: outputFile,
    })

    return {
      formattedSchema,
      outputFile,
      schema,
      schemaGeneratorConfig,
      stringifiedSchema,
    } as const satisfies EntryWithSchema & {
      formattedSchema: string
      stringifiedSchema: string
    }
  }),
)

const createJsonSchema = async () => {
  await Promise.all(
    stringifiedSchemas.map(({ outputFile, formattedSchema }) =>
      fs.writeFile(outputFile, formattedSchema, { encoding: 'utf8' }),
    ),
  )
}

createJsonSchema()
