name: autofix.ci

on:
  pull_request:

permissions:
  contents: read

jobs:
  autofix:
    if: github.repository == 'rolldown/tsdown'
    runs-on: ubuntu-latest
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@340b33de8349804cfdae4f42345478516d03a973
        with:
          no-frozen-lockfile: true

      - name: Format
        run: pnpm run format

      - name: Lint
        run: pnpm run lint --fix

      - name: Update API snapshots
        run: pnpm build --update-snapshot

      - name: Commit
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
