name: Publish Any Commit
on: [push, pull_request]

permissions: {}

jobs:
  release:
    if: github.repository == 'rolldown/tsdown'
    name: Release Commit
    runs-on: ubuntu-latest
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@340b33de8349804cfdae4f42345478516d03a973

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm dlx pkg-pr-new@0.0 publish --pnpm --compact . './packages/*' --packageManager=pnpm,npm,yarn --commentWithDev
