name: Unit Test

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@340b33de8349804cfdae4f42345478516d03a973

      - name: Type Check
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [22, 24, 26]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@340b33de8349804cfdae4f42345478516d03a973
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: pnpm run build

      - name: Unit Test
        run: pnpm run test
